version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=development
      - PORT=3001
      - CORS_ORIGIN=http://localhost:8080
    command: npm run dev

volumes:
  postgres_data: 