version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: ViberLounge
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: api_container
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=ViberLounge;Username=admin;Password=admin123
  #   depends_on:
  #     - postgres

volumes:
  pgdata:
